### ISSUE TITLE
Dokumentation hinzufügen, wie man AudioCues anlegt/abspielt

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#119]
### Beschreibung

Dokumentation hinzufügen, wie man AudioCues anlegt/abspielt

**Comment by fastFox2** [comment]
.meine-aufgabe

**Comment by fastFox2** [comment]
Kurzes Update: Bin dran, war aber IRL viel los und gehe ins Trainingslager für eine Woche.
