### ISSUE TITLE
"Weiterlesen" Links auf Projekt Website sind "irreführend"

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#129]
### Beschreibung

Auf der Website des Community Projekts https://boundfoxstudios.github.io/community-project/ sind mehrere "Weiterlesen..." Links. Diese leiten auf Youtube, Discord und GitHub zurück, was man nicht unbedingt intuitiv erwarten würde.

Zur Zeit gibt es wohl keine Möglichkeit diese Links weiter anzupassen, vielleicht aber mit einem zukünftigen Update.

**Comment by ManuelRauber** [comment]
.meine-aufgabe
