### ISSUE TITLE
[Bug]: _gameSettings NullRefException in rare cases

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#136]
### Fehlerbeschreibung

In seltenen Fällen verursacht das SettingsSystem beim Versuch die Einstellungen auf das Spiel anzuwenden eine NullRefException.
Zu diesem Zeitpunkt hat das SettingsSO noch im Feld private GameSettings _gameSettings den Wert null.

### Wie kann man den Fehler reproduzieren?

Bei Spieltstart. Bisher nur bei InitializationLoader reproduzieren können, dabei auch eher nach Editor Neustart.

### Erwartetes Verhalten

Spielt lädt Einstellungen und wendet diese an.

### Betriebssystem

Windows 10

### Spiel-Version

0.1

### Sonstiges

![grafik](https://user-images.githubusercontent.com/18291863/200532852-2a2c26c6-09ce-4292-bef2-e1effd2f2793.png)
![grafik](https://user-images.githubusercontent.com/18291863/200536897-010dfbb9-2089-4811-8828-835e24d59d68.png)

Trace:
NullReferenceException: Object reference not set to an instance of an object
BoundfoxStudios.CommunityProject.Settings.ScriptableObjects.SettingsSO.get_Audio () (at Assets/_Game/Scripts/Runtime/Settings/ScriptableObjects/SettingsSO.cs:17)
BoundfoxStudios.CommunityProject.Settings.SettingsSystem.ApplyAudioSettings () (at Assets/_Game/Scripts/Runtime/Settings/SettingsSystem.cs:50)
BoundfoxStudios.CommunityProject.Settings.SettingsSystem.ApplySettings () (at Assets/_Game/Scripts/Runtime/Settings/SettingsSystem.cs:42)
BoundfoxStudios.CommunityProject.Settings.SettingsSystem.Awake () (at Assets/_Game/Scripts/Runtime/Settings/SettingsSystem.cs:27)

**Comment by ManuelRauber** [comment]
@M4lph Kannst Dir schnappen :)
