### ISSUE TITLE
Übernahme Miro-Karte "Loop-basiertes Gameplay" ins GDD

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#140]
### Beschreibung

Bitte zuerst #139 lesen.

Datei im GDD: `loop-gameplay/index.md`.
Weitere Info stehen in dieser Datei.

**Comment by fastFox2** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
@allcontributors please add @fastFox2 for ideas
