### ISSUE TITLE
Übernahme Miro-Karte "Rasterbasiertes Bauen" ins GDD

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#142]
### Beschreibung

Bitte zuerst #139 lesen.

Datei im GDD: `construction/index.md`.
Weitere Info stehen in dieser Datei.

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
@allcontributors please add @M4lph for ideas
