### ISSUE TITLE
[Bug]: Scheinbar keine Nutzung von Caches im Build

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#171]
### Fehlerbeschreibung

Laut https://github.com/BoundfoxStudios/community-project/actions/caches werden keine Caches genutzt. 

### Wie kann man den Fehler reproduzieren?

Build laufen lassen.

### Erwartetes Verhalten

Caches werden genutzt

### Betriebssystem

Anderes (bitte in der Fehlerbeschreibung angeben)

**Comment by ManuelRauber** [comment]
Alles wird. Wird benutzt, war nur zu alt und daher nicht mehr in der Liste drin. 👍

**Comment by fastFox2** [comment]
Kann man dann nicht schließen wenn alles nach Plan funktioniert?
