### ISSUE TITLE
Basis-SO für Gegner

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#180]
### Beschreibung

https://boundfoxstudios.github.io/community-project/docs/ideas/enemies/

Alle Gegner teilen sich gewisse Werte, die als Basis-SO festgehalten werden können:

- [ ] Name (lokalisierbar)
- [ ] Lebenspunkte (int)
- [ ] Rüstung (int)
- [ ] Geschwindigkeit (float)
- [ ] Größe (float)
- [ ] Erfahrungspunkte (int, erhält der Spieler bei erfolgreichem Töten)
- [ ] Münzen (int, erhält der Spieler bei erfolgreichem Töten)

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
@M4lph Jetzt kannste :)

**Comment by M4lph** [comment]
.meine-aufgabe
