### ISSUE TITLE
Anzeige Turmreichweite

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#194]
### Beschreibung

Im Editor wird bereits über das Gizmos-System eine kleine Darstellung angezeigt, um zu sehen, wie weit ein Turm feuern kann:

![image](https://user-images.githubusercontent.com/740791/213872446-7f1a8272-b5b9-4ec0-840b-32dae73c3f37.png)

InGame sieht der Spieler davon beim Platzieren des Turmes allerdings leider nichts. 
Es benötigt daher eine Anzeige, die dem Spieler anzeigt, wie weit der Turm schießen kann.

Als Idee könnte man z.B. einen LineRenderer benutzen, eventuell könnte man auch mit einem DecalProjector arbeiten.

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by M4lph** [comment]
ShaderGraph macht mir leider doch noch etwas Probleme, bin aber halbwegs zuversichtlich das noch hin zu bekommen.
