### ISSUE TITLE
Veränderung der Turmreichweite durch erhöhte Positionen

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#195]
### Beschreibung

Aktuell hat ein Turm eine fixe Reichweite. 
Da wir im 3D-Space sind könnten wir die Reichweite vom Turm erhöhen, sofern er auf einer erhöhten Position platziert wird.

Allerdings muss man aufpassen, da durch den Turm die Waffe bereits auf einer erhöhten Position ist. Das soll allerdings der "nullpunkt" sein und nur erhöhte Positionen ergeben mehr Reichweite.

Cool wäre es, wenn man das beim Turm nicht einstellen muss, sondern der Turm seinen Nullpunkt selbst rausfindet.

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by M4lph** [comment]
Ist noch in Arbeit mit Pr#217, werde den aber noch erledigen :)
