### ISSUE TITLE
Refactoring von TargetLocator bzgl. Auswahl der Ziele

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#200]
### Beschreibung

Aktuell beinhaltet der TargetLocator den Code um je nach TargetType den richtigen Gegner zu bekommen. 
Das sollte refactored werden, da die Klasse sonst recht lang wird, wenn noch weitere TargetTypes hinzukommen.

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by M4lph** [comment]
.meine-aufgabe
