### ISSUE TITLE
Umbenennen von Eigenschaften, die namentlich aktuell nicht passen

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#203]
### Beschreibung

- [ ] `WeaponSO.FireRatePerSeconds`: Suggeriert aktuell, dass x-mal pro Sekunde gefeuert wird. Stimmt nicht, es ist ein "Feuert alle X Sekunden"
- [ ] `BallisticWeaponSO.(Launch/Rewind)AnimationSpeed`: Beschreibt nicht die Geschwindigkeit der Animation, sondern die Zeit in Sekunden

Bitte beim Umbenennen beachten, dass auch abhängige Variablen mit umbenannt werden.

**Comment by SuperPirate-ai** [comment]
.meine-aufgabe
