### ISSUE TITLE
Implementierung GameManager

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#206]
### Beschreibung

- [x] Verbindung zum #184 -> startet die Wellen nach dem alles geladen wurde
- [x] Muss erkennen können, dass Spieler kein Leben mehr hat oder alle Gegner besiegt wurden
- [ ] Pause-Funktion, #209 

Ist voraussichtlich nicht alles in einer Klasse, sondern in mehreren zu implementieren.

Auf jeden Fall bitte vorher Rücksprache in Discord halten.

**Comment by M4lph** [comment]
Tasks 1&2 sind erledigt eigtl oder?
Für Pausenmenü extra Issue anlegen?

**Comment by M4lph** [comment]
Korrigiere, aktuell wird nicht erkannt ob alle Gegner besiegt wurden :)

**Comment by ManuelRauber** [comment]
> Tasks 1&2 sind erledigt eigtl oder? Für Pausenmenü extra Issue anlegen?

Siehe #209 

> Korrigiere, aktuell wird nicht erkannt ob alle Gegner besiegt wurden :)

Das ist korrekt, dafür gerne in issue :)
