### ISSUE TITLE
Implementierung: Pausenmenü

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#209]
### Beschreibung

Kleines Pausemenü mit 2 Buttons:

- [ ] Weiter, setzt das Spiel fort
- [ ] Hauptmenü, geht zurück zum Hauptmenu

Wird #206 zuvor benötigen, um das Spiel in Pause zu versetzen.
Zu implementieren ist das Menü später in einer eigenen Scene, die wir additiv dazu laden.

**Comment by M4lph** [comment]
.meine-aufgabe
