### ISSUE TITLE
Tooltip System

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#211]
### Beschreibung

Implementierung eines Tooltip-Systems für UI-Elemente:

- [ ] Eigenes Canvas in der Persistent Scene 
- [ ] Ein Element in diesem Canvas, was den Rahmen für den Tooltip abbildet 
- [ ] Zum Start reicht im Tooltip ein simples TextMeshPro
- [ ] EventChannel zum Öffnen eines Tooltips
- [ ] EventChannel zum Schließen eines Tooltips
- [ ] Positionierung des Tooltips sollte in der Nähe der Maus sein, idealweise in Richtung Mitte des Bildschirms verschoben (dann spielt es keine Rolle, wie groß das Tooltip ist und ob ein Element sehr weit am Rand ist oder nicht)
- [ ] Beim Enter auf ein Element, dass ein Tooltip hat, wird das Event ausgelöst zum Öffnen des Tooltips
- [ ] Beim Leave auf ein Element, dass ein Tooltip hat, wird das Event ausgelöst zum Schließen des Tooltips

### Tooltip Interface

```cs
interface ITooltip {
  // Auch wenn wir's erst nur im UI nutzen, starten wir direkt mit Vector3, sodass es später auch für GameObjects nutzbar ist
  Vector3 Position { get; } 
}

interface ITextTooltip : ITooltip {
  string Text { get; }
}

// Ideen für später:
interface IBuildableTooltip : ITooltip {
  // Name des Turms, der gebaut werden soll
  string Name { get; }

  // Wie viel der Turm kostet
  int Coins { get; }
}

// Maximal flexibilste Tooltips, da wir hier ein Prefab instanziieren:
interface IPrefabTooltip : ITooltip {
  GameObject Prefab { get; }
}
```

### EventChannel

Der EventChannel erhält als Argument ein `ITooltip`, sodass alle Tooltips genutzt werden können.

### TooltipManager

MonoBehaviour, das in der persistent Scene lebt und die Events anbindet.
Entscheidet je nach Tooltip-Typ, welches angezeigt wird.

**Comment by SuperPirate-ai** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Hi @SuperPirate-ai,

freut mich, dass Du diese Aufgabe angehen möchtest! :)

Es wäre super, wenn Du Dir vorab einige Gedanken machst, wie Du es implementieren möchtest, bevor Du loslegst. Dann können wir am Anfang direkt überlegen, ob wir die richtige Richtung einschlagen.

Danke!

**Comment by SuperPirate-ai** [comment]
Ja klar, 
ich hatte vor, wie Du vorgeschlagen hast, ein Interface für die ToolTips zu implementieren. Dann würde ich ein Script erstellen, welches jedes Objekt bekommt, das ein ToolTip aufrufen soll. Dieses Skript implementiert dann von IToolTip oder IToolTipText. Dann sollte dieses Skript einen string 'tip' haben, der als SerializeField makiert ist. (Später kann man natürlich dies auch für GameObjekts machen) So könnte man dann vom Inspektor aus den Tip individuell einfügen und diesen dann als Text des tooltips deklarieren. Dann könnte das Skript eine OnMouseEnter/OnMouseExit Methode haben um quasi zu triggern wenn der ToolTip angezeigt werden soll. In den Methoden wir dann ein Event aufgerufen(wahrscheinlich sowas wie "OpenToolTip" und "CloseToolTip"), welches sich im EventChanel SkriptableObject befindet. Dieses Event hat als delegateparameter dann den string tip, der übergeben wird . Im ToolTip Manager suscriben wir zum event und aktivieren in einer Methode den ToolTipText im Canvas in der PresistentManagers Scene und fügen den tipText hinzu. Die Positionierung des Tips würde ich ebenfalls im ToolTipManager machen. Däfür würde ich die MousePosition als Refernez zur Position des Tips nehmen und dann jenachdem wo die Maus ist (also oben im Screen links rechts) die Position des toltipTextes so anpassen,dass er bei der maus, zur mitte schauend plaziert ist.

Das ist jetzt dann mal so die Gedanken die ich mir danzu gemacht habe. :)
Falls du findest, dass man manche Sachen anders machen sollte, kannst du dich gerne dazu äußern. Ich bin für jedes Feedback dankbar.

**Comment by ManuelRauber** [comment]
@SuperPirate-ai 

Das klingt doch soweit erstmal gut, ein paar kleine Anmerkungen hab ich:

> Dann könnte das Skript eine OnMouseEnter/OnMouseExit Methode haben um quasi zu triggern wenn der ToolTip angezeigt werden soll.

Die `OnMouseEnter` und `OnMouseExit` funktionieren bei uns nicht, da wir das neue InputSystem im Einsatz haben. Die gibt's nur beim alten System auf Meshes mit Collidern.
Alternativ kannst Du aber die Unity-Interfaces `IPointerEnter` und `IPointerExit` implementieren, die sind zumindest mal für UI-Elemente.
Für Meshes mit Collider, also wenn man z.B. über einen Tower hovern würde, müsste man was eigenes implementieren.
Es würde mir daher erstmal reichen, wenn Du es nur für UI-Elemente machst. 

> Die Positionierung des Tips würde ich ebenfalls im ToolTipManager machen. Däfür würde ich die MousePosition als Refernez zur Position [...]

Die MausPosition könntest Du Dir über den InputReader holen. Der hat allerdings noch nix für permanentes Tracking der Maus. Würde folgendes Vorschlagen:

1. Der InputReader (bzw. das Asset für das InputSystem) bekommt eine neue Kategorie für Tooltips
2. Dort drin dann eine Action zum Tracking der MausPosition (äquivalent zu der Action im BuildSystem).
3. Wenn Dein Script erkennt, dass ein Tooltip angezeigt werden muss (`IPointerEnter`), schaltet es auf dem InputReader auch die Kategorie für das Tooltip ein, sodass das Tracking beginnen kann.
4. Wenn Dein Script erkennt, dass der Tooltip versteckt werden muss (`IPointerExit`), können wir auch das Tracking wieder ausschalten. 
5. Der TooltipManager kann sich dann an den InputReader hängen und sofern dann Daten kommen, diese entsprechend verarbeiten. 

So als erster Gedanke, müssen wir mal schauen, ob das taugt und funktioniert. :)

**Comment by SuperPirate-ai** [comment]
Das tooltip-system funktionieren soweit. Warte nur noch auf ein Review ;)

**Comment by ManuelRauber** [comment]
Closed durch #254
