### ISSUE TITLE
Implementierung von Graphy

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#234]
### Beschreibung

Implementierung von Graphy: https://github.com/Tayx94/graphy

Sollte im Editor und im Development-Mode zur Verfügung stehen, aber nicht mehr im Release-Build. 

Dazu bitte ein Tag `DevelopmentOnly` anlegen (ähnlich wie bei EditorOnly-Tag) und ein Script, dass alle Objekte einer Scene löscht, die dieses Tag haben, sobald das Spiel gebaut wird. Dazu wird das Interface `IProcessSceneWithReport` benötigt, siehe [hier](https://docs.unity3d.com/ScriptReference/Build.IProcessSceneWithReport.html). 

Vom Aufbau erzeugen wir ein eigenes Prefab in das wir das Prefab von Graphy legen.
Das `DevelopmentOnly`-Tag erhält auch unser Prefab.
Unser Prefab legen wir dann in der Scene `PersistentManagers` ab.

Installation von Graphy bitte via git-URL.

**Comment by SuperPirate-ai** [comment]
.meine-aufgabe
