### ISSUE TITLE
Anzeigen der Waffenreichweite bei Platzieren und Auswählen von Waffen

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#246]
### Idee/Feature-Beschreibung

- [ ] Anzeige während dem Platzieren von Waffen. Muss auch Änderungen der Reichweite z.B. bei höherer Platzierung von ballistischen Türmen beachten.
- [ ] Anzeige bei Auswahl der Waffe.

**Comment by ManuelRauber** [comment]
Hab das Label entfernt :)
