### ISSUE TITLE
[Bug]: RandomTargetType bei Catapult Tower wirft NullRefException

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#262]
### Fehlerbeschreibung

TargetLocator nutzt PickRandom() extension auf einem Array mit Length = 50, das z.Bsp. 39 null refs hat, und an der Stelle von den 11 übrigen nur 2 im tatsächlichen Angriffssegment sind.

![grafik](https://user-images.githubusercontent.com/18291863/230872988-d5e60825-516b-46e6-a9b9-748df449e8df.png)

### Wie kann man den Fehler reproduzieren?

Catapult Prefab auswählen, in BallisticWeapon Behaviour bei TargetType Random auswählen.

### Erwartetes Verhalten

Keine NullRefException :)

### Betriebssystem

Windows 10

**Comment by ManuelRauber** [comment]
.meine-aufgabe
