### ISSUE TITLE
BuildTargetGroup ist als veraltet markiert

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#278]
### Beschreibung

Derzeit werden zur Integration in Steam an verschiedenen Stellen im Code die Methoden Set-/GetScriptingDefineSymbolsForGroup() genutzt, deren 1.Parameter die BuildTargetGroup ist.

Laut Dokumentation https://docs.unity3d.com/2022.2/Documentation/ScriptReference/PlayerSettings.SetScriptingDefineSymbolsForGroup.html ist diese Variante veraltet (seit 2021, mit 2023 nochmal deutlicher als obsolet markiert).

**Comment by ManuelRauber** [comment]
@M4lph wolltest Du Dir das anschauen?

**Comment by M4lph** [comment]
.meine-aufgabe
