### ISSUE TITLE
Aktualisierte Farbpalette

### ISSUE THREAD

**Issue by ProTools3000** [BoundfoxStudios/community-project#280]
### Idee/Feature-Beschreibung

Bestünde die Möglichkeit, die Farbpalette auch anderweitig zu beziehen? Sonst müsste ich zwangsläufig jedesmal das Kit downloaden, wenn ich doch eigentlich nur die aktualisierte Farbpallette benötige.

**Comment by ManuelRauber** [comment]
@allcontributors please add @ProTools3000 for design, idea

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ProTools3000** [comment]
@ManuelRauber 
added colors:
grey1 - #808080
grey2 - #404040
grey3 - #222222

**Comment by ManuelRauber** [comment]
Fixed in 2d55685538008b96860767ac8d3d59ed9ec20d35

Download hier: https://docs.fairytaledefender.de/docs/docs-visual/colors/ -> Sommer -> Download
