### ISSUE TITLE
Prüfen ob static Flags auf Modellen mit Windshader funktionieren

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#283]
### Beschreibung

Aktuell sind die meisten Modelle als Static markiert, sprich auch als static Ocluder/Ocludee. Da wir z.Bsp. einen Wind Shader benutzen, der die Vertices unserer Meshes beinflusst, sollte geprüft werden ob es mit diesen Einstellungen zu Konflikten/Problemen kommt.

Laut einem sehr alten Thread könnte es dabei zu visuellen Glitches kommen - siehe https://answers.unity.com/questions/645132/clarification-on-static-batching-a-shader-animated.html

**Comment by ManuelRauber** [comment]
.meine-aufgabe

Hab's mal direkt bei Unity eingetütet, mal schauen, ob da was kommt. :)

**Comment by ManuelRauber** [comment]
Erst Antwort kam bereits: Man würde was bemerken, wenn man baked lights hat, da diese dann nicht mehr aktualisiert werden.
Ansonsten bedeutet static wirklich das movement vom Transform und nicht von der Vertices.

Mal schauen, ob die Tage noch ein bisschen mehr dazu kommt.

**Comment by ManuelRauber** [comment]
Jut, es kamen die gleichen Antworten zur Bestätigung, sollte daher in unserem Fall, da wir weder baked lights haben noch eine großartige Verschiebung der Vertices machen, zu Probleme führen. :)
