### ISSUE TITLE
Blender Export Script: parents

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#286]
### Beschreibung

Manche Modelle haben bewegliche Teile (z.B. Katapult) und bestehen deshalb aus mehreren Objekten. Wobei das bewegliche Objekte als übergeordnete Element aufs ("set parent to") starre Objekt gesetzt wird.

Beim Export mittels Script wird diese Verbindung getrennt und die beiden Objekte werden als separate FBX Datei angelegt.
Hierfür wird eine Änderung am Script benötigt das "parents" erkennt und korrekt, in einer Datei, exportiert.

[Prop_Katapult-Export.blend.zip](https://github.com/BoundfoxStudios/fairy-tale-defender/files/11308014/Prop_Katapult-Export.blend.zip)

**Comment by ManuelRauber** [comment]
@DIY-Blub Kannst du mir bitte hier noch ein Blendfile anhängen?

**Comment by ghost** [comment]
@ManuelRauber liegen auf Discord: https://discord.com/channels/454361389935493124/1097583795470864414/1098888733190783037

**Comment by ManuelRauber** [comment]
> @ManuelRauber liegen auf Discord: https://discord.com/channels/454361389935493124/1097583795470864414/1098888733190783037

Danke, ich habs in deinem initialen Post mal angehängt. :)
