### ISSUE TITLE
[Bug]: Anzeigefehler Schuss-Reichweite vom Turm (Linux?)

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#298]
### Fehlerbeschreibung

Die Schuss-Reichweite vom Turm wird als riesige Fläche angezeigt. siehe Screenshot / Video unter Sonstiges

### Wie kann man den Fehler reproduzieren?

Versionen und Log unter Sonstiges

### Erwartetes Verhalten

In den Videos von Manu ist die Anzeige der Reichweite korrekt.

### Betriebssystem

Linux (genaue Distribution bitte in der Fehlerbeschreibung angeben)

### Spiel-Version

Build-ID: 11114425, vom 28.April 2023 um 20:54

### Sonstiges
Linux Mint 21 Cinnamon 5.4.12
Linux-Kernel: 5.15.0-71-generic

https://user-images.githubusercontent.com/60984430/235236051-117ba23f-e971-499c-9fa7-51d83a2ae33e.mp4
![Bildschirmfoto vom 2023-04-28 21-34-35](https://user-images.githubusercontent.com/60984430/235237270-f2dcdc92-5200-4264-879d-d7d0aafc6c82.png)

[Player.log](https://github.com/BoundfoxStudios/fairy-tale-defender/files/11356786/Player.log)

**Comment by ManuelRauber** [comment]
@DIY-Blub Kannst du in Steam bitte einmal Rechtsklick auf das Spiel machen und dort bei General bei "Launch Options" einmal exakt das hier einzugeben: `-force-vulkan` 

Schau mal bitte, ob es dann startet und der Fehler noch ist. Falls nicht, gerne Screenshots und so posten. :)

![image](https://user-images.githubusercontent.com/740791/235433376-604f3da7-aa50-4e34-8404-c5ff98249039.png)

**Comment by ghost** [comment]
@ManuelRauber Der Turm passt jetzt!! :+1:  ... diese 2 Fehlermeldungen sind noch vorhanden:
![Bildschirmfoto vom 2023-05-01 22-05-06](https://user-images.githubusercontent.com/60984430/235522042-ff5b66fe-1ded-4ef4-8b26-50a8fc00d013.png)

PS: entscheide bitte selbst ob damit das Issue abgeschlossen ist :)

**Comment by ManuelRauber** [comment]
> @ManuelRauber Der Turm passt jetzt!! :+1:  ... diese 2 Fehlermeldungen sind noch vorhanden:
> 
> ![Bildschirmfoto vom 2023-05-01 22-05-06](https://user-images.githubusercontent.com/60984430/235522042-ff5b66fe-1ded-4ef4-8b26-50a8fc00d013.png)
> 
> 
> 
> PS: entscheide bitte selbst ob damit das Issue abgeschlossen ist :)

Sehr gut. 

Dann nimm diese Option bitte wieder aus den Steam-Einstellungen raus. Werde es im Projekt umstellen, sodass es dann bei der nächsten Aktualisierung korrekt sein sollte. 

Bei den anderen Fehlern bin ich dran. Einer davon wird bleiben, da wir noch keine Musik haben 😄

**Comment by ManuelRauber** [comment]
Bitte nicht schließen, Fehler ist noch nicht behoben.
