### ISSUE TITLE
[Idee/Vorschlag]: Studio Bilder/Videosequenzen (Blender)

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#311]
### Idee/Feature-Beschreibung

Ein Studio in Blender zur Erstellung von Bilder (Renderings) und Videosquenzen für das Spiel.

Das Archiv [Blender-Studio.zip](https://github.com/BoundfoxStudios/fairy-tale-defender/files/11383871/Blender-Studio.zip) beinhaltet:
* Blenderfile vom Studio
* Screenshot von der Blenderfile
* Entwurf für eine Unterseite unter Dokumentation

Screenshot von der Blenderfile:
![Blender-Studio](https://user-images.githubusercontent.com/60984430/235957676-7d1e38d7-9b45-4b89-8f47-8be3079a3a4d.png)

**Comment by ManuelRauber** [comment]
Beim Studio benötige ich noch etwas Arbeit von Dir:
![image](https://user-images.githubusercontent.com/740791/235990863-91efa1ff-d2ae-43a6-a5e7-b516f38c3026.png)

Die Blendfiles heißen anders bei uns im Repo, daher wird die Verknüpfung nicht funktionieren. Die Blendfiles liegen alle hier: https://github.com/BoundfoxStudios/fairy-tale-defender/tree/develop/resources/Blendfiles. Ich würde auch genau dort das Studio ablegen. 

Wie schwer ist das, das ganze neu zu verknüpfen?

**Comment by ghost** [comment]
neu verknüpft :)
[Blender-Studio.blend.zip](https://github.com/BoundfoxStudios/fairy-tale-defender/files/11388471/Blender-Studio.blend.zip)
