### ISSUE TITLE
[Idee/Vorschlag]: Rotkäppchen (3D-Modell)

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#312]
### Idee/Feature-Beschreibung

3D-Modell von Rotkäppchen

Blenderfile: [Redcap.blend.zip](https://github.com/BoundfoxStudios/fairy-tale-defender/files/11384075/Redcap.blend.zip)

Screenshot mit Wolf:
![Redcap-Screenshot_with_Wolf](https://user-images.githubusercontent.com/60984430/235959898-c9f59617-b1eb-44d2-9285-76f5b5789cc8.png)

**Comment by ManuelRauber** [comment]
@DIY-Blub Merci!

Rotkäppchen heißt übrigens auf Englisch: Little Red Riding Hood 😬

**Comment by ghost** [comment]
Ja stimmt, so heisst auch die Collection. Ich dachte als Objektbezeichnung ist ein Einzelwort, deshalb "Redcap". Obwohl da die diversen Suchmaschinen unterschiedliches dazu ausspucken :laughing: 
Wie du willst, kannst es ja umbenennen :+1:
