### ISSUE TITLE
Türme sollten nicht mehr direkt "ausgewählt" werden nach Bauen

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#325]
### Idee/Feature-Beschreibung

Aktuell wird nachdem ein Turm gebaut wurde, sofort ein weiterer Raycast in die Scene gemacht, welcher wiederrum z.Bsp. sofort den gerade gebauten Turm "auswählt", oder im Grenzfall einen benachbarten Turm, was auch irritirend sein kann:

https://user-images.githubusercontent.com/18291863/236312900-ae6c9b10-023a-4d0b-abaf-e5e2ef5fbffb.mp4

**Comment by ghost** [comment]
Meiner Meinung nach ist das sogar ein Bug. Sollte auf alle Fälle "behoben werden"! :)

**Comment by ManuelRauber** [comment]
.meine-aufgabe
