### ISSUE TITLE
[Idee/Vorschlag]: Implementierung einer In-Editor Scene Auswahl

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#33]
### Idee/Feature-Beschreibung

Siehe hier für mehr Informationen: https://manuel-rauber.com/2022/03/14/unity-tip-level-selection-editor-window/

**Comment by realTobby** [comment]
.meine-aufgabe

**Comment by realTobby** [comment]
@ManuelRauber Wohin soll das LevelSelection Menü? Ich denke mal unter "Community Project" oder?

**Comment by realTobby** [comment]
@ManuelRauber Wie genau kann man aus dem Editor.csproj heraus auf die PersitentScene zugreifen um die Scenes zu laden? Muss ich auf die Adressables noch einen Verweis hinzufügen? So ganz verstehe ich die Infratruktur noch nicht :D Bräuchte denke ich nur einen "rotenfaden"-Anfang wie das SceneManagement momentan gelöst ist. Danke!

**Comment by ManuelRauber** [comment]
Klingt gut, ja --Beste Grüße Manuel RauberOn 27. Sep 2022, at 21:26, Tobby ***@***.***> wrote:﻿
@ManuelRauber Wie genau kann man aus dem Editor.csproj heraus auf die PersitentScene zugreifen um die Scenes zu laden? Muss ich auf die Adressables noch einen Verweis hinzufügen? So ganz verstehe ich die Infratruktur noch nicht :D Bräuchte denke ich nur einen "rotenfaden"-Anfang wie das SceneManagement momentan gelöst ist. Danke!

**Comment by ManuelRauber** [comment]
> @ManuelRauber Wie genau kann man aus dem Editor.csproj heraus auf die PersitentScene zugreifen um die Scenes zu laden? Muss ich auf die Adressables noch einen Verweis hinzufügen? So ganz verstehe ich die Infratruktur noch nicht :D Bräuchte denke ich nur einen "rotenfaden"-Anfang wie das SceneManagement momentan gelöst ist. Danke!

Danke für den Hinweis, ergänze ich morgen in der Doku und schreib hier was rein :)

**Comment by ManuelRauber** [comment]
> @ManuelRauber Wie genau kann man aus dem Editor.csproj heraus auf die PersitentScene zugreifen um die Scenes zu laden? Muss ich auf die Adressables noch einen Verweis hinzufügen? So ganz verstehe ich die Infratruktur noch nicht :D Bräuchte denke ich nur einen "rotenfaden"-Anfang wie das SceneManagement momentan gelöst ist. Danke!

~Das Laden von Addressables im Editor ist was, an dem Unity noch arbeitet.~ Gerade gesehen, dass es seit letzter Version implementiert ist: https://forum.unity.com/threads/how-to-use-addressable-system-in-editor-script.715163/#post-8469452

Aber, das brauchen wir hier tatsächlich (noch) nicht. Du musst eigentlich nur den Blog-Post von mir durcharbeiten und 1:1 implementieren.

Die Szenen zum Laden sprechen wir einfach über deren Pfad im Dateisystem an.

Über Addressables wäre natürlich cool, aber da müssen wir erstmal gucken, ob das wirklich schon so funktioniert, wie man sich das vorstellt. Werd ich im Zuge vom PrefabManager mal ausprobieren und schauen.

Für's erste reicht es, wenn wir die Szenen ganz normal über den Pfad ansprechen und laden. :)
