### ISSUE TITLE
[Idee/Vorschlag]: Grasflecken

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#333]
### Idee/Feature-Beschreibung

Damit die grüne Tiles-Oberfläche etwas mehr hergibt könnte man einige Grasflecken auf der Map verteilen. 

**kleines Beispiel aus Blender für besseres Verständnis:**
![example-blender](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/60984430/4bd48f1b-199f-421a-a38c-dcf738886ed8)

**Unity:** Ideal wäre wenn die Grasflecken zufällig auf der Map verteilt (vielleicht mittels SubShader) werden, ohne das man manuell Objekte platziert.

**Comment by ManuelRauber** [comment]
![image](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/740791/9053cda7-c060-43c4-8289-790322c4bfe6)

erster Test in Unity.

**Comment by ghost** [comment]
@ManuelRauber ja, gibt schon was her :+1:  Ich würd sagen wir nehmen es in das nächste Steam-Update mit rein und warten auf Feedback. Okay?

**Comment by ManuelRauber** [comment]
> @ManuelRauber ja, gibt schon was her 👍 Ich würd sagen wir nehmen es in das nächste Steam-Update mit rein und warten auf Feedback. Okay?

Ich brauch dafür nur aktualisierte Tiles:

1. Die Oberfläche benötigt ein eigenes Material, bspw. mit dem Namen "Surface".
2. Eine 2. UV Map, die genau diese Oberfläche neu mappt, komplett von 0/0 bis 1/1

Wir können es nur bei den vollflächigen Tiles machen. Alle anderen können wir nicht mit der Art und Weise mit dem Shader verarbeiten lassen.

**Comment by ghost** [comment]
> Wir können es nur bei den vollflächigen Tiles machen.  Alle anderen können wir nicht mit der Art und Weise mit dem Shader verarbeiten lassen.
![grasflecken](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/60984430/a70dab5f-3a2d-4e2a-a6f5-14231f65eefb)

Dann müssten aber viel weniger machen, sonst sieht es doch etwas komisch aus... was meinst du dazu?
Kann man in Unity nur auf (beispielsweise) jedes Dritte per Zufall einen Grasfleck machen?

**Comment by ManuelRauber** [comment]
Aktuell hab ich pro Tile 2 Flecken. Wir könnten natürlich auch nur einen Flecken pro Tile machen. 
Jeder Dritte oder so geht "nicht" (ging schon, aber der Aufwand dahinter rechtfertigt es glaub ich nicht). Man könnte maximal noch zufällig ein/ausschalten.

**Comment by ghost** [comment]
Es sieht halt etwas komisch aus wenn auf jedem "normalen" Feld 1-2 Flecken sind, aber dann bei den schrägen/schiefen Feld gar keine Flecken sind. Finde nur ich als komisch :grey_question: 

Ich würd sagen wir lassen das Thema mal ruhen. Hat echt keine Priorität bzw. Notwendigkeit... ist ja nur ein dekoratives Thema.

**Comment by ManuelRauber** [comment]
> Es sieht halt etwas komisch aus wenn auf jedem "normalen" Feld 1-2 Flecken sind, aber dann bei den schrägen/schiefen Feld gar keine Flecken sind. Finde nur ich als komisch ❔
> 
> Ich würd sagen wir lassen das Thema mal ruhen. Hat echt keine Priorität bzw. Notwendigkeit... ist ja nur ein dekoratives Thema.

Moooment. :) Das funktioniert!

Es funktionieren nur keine Tiles, die keine gleichbleibende Oberfläche haben, z.B. jedes Wege-Tile, das ja ein Stück Weg, aber auch ein Stück "Gras" hat. Die gehen nicht.

Alle anderen, also Flat, Corner_Inner, Corner_Outer, Slope, die funktionieren. :)

**Comment by ghost** [comment]
asooooooo! na dann machen wir es.

**Comment by ghost** [comment]
.meine-aufgabe
