### ISSUE TITLE
[Idee/Vorschlag]: Gegner hat Haus erreicht

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#341]
### Idee/Feature-Beschreibung

Vorschlag bezüglich "Gegner hat Haus erreicht": kurzgesagt das man die Darstellung der Tür verändert (wird etwas kaputter darstellt).

Dafür bräuchte man mehrere Varianten der Tür, die dann ausgetauscht werden. Hier mal ein schneller Vorschlag zur Darstellung:

1. leichter Schaden: zerkratzt (z.B. andere Farbe)
2. schwerer Schaden: Stücke in der Tür fehlen
3. Tür zerstört: Tür entfernt, nächster Gegner --> game over

Ich denke 1-2 Darstellungen für "leichter Schaden" und 2-3 Darstellungen für "schweren Schaden" sollten genügen.

Das Haus müsste man ebenfalls noch überarbeiten, cool wäre wenn man ein paar Möbelstücke durch die Lücken sieht.

**Comment by ManuelRauber** [comment]
Idee gefällt. Muss nur jemand modellieren. :)

**Comment by ghost** [comment]
.meine-aufgabe

**Comment by ghost** [comment]
neues Haus - Modell kommt noch diese Woche

**Comment by ManuelRauber** [comment]
Ich schnapp mir die Aufgabe mal, da der PR ja existiert, aber noch nicht von mir bearbeitet wurde. :)
