### ISSUE TITLE
[Bug]: Null Ref Exception bei Szenenwechsel

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#344]
### Fehlerbeschreibung

CameraRuntimeAnchor hat während Szenenwechsel keine Referenz mehr zu einer Kamera.
Wenn also ein System wie SelectionController versucht während dessen darauf zu zugreifen, wird eine Exception geworfen.

### Wie kann man den Fehler reproduzieren?

Gameplay starten -> linke Maustaste halten bevor Gegner Leben auf 0 reduzieren -> Szenenwechsel abwarten

### Erwartetes Verhalten

Keine Null Ref-Exception :)

### Betriebssystem

Windows 10

### Sonstiges

Logs/Stacktraces:
NullReferenceException: obj is null
BoundfoxStudios.FairyTaleDefender.Extensions.ObjectExtensions.EnsureOrThrow[T] (T obj) (at Assets/_Game/Scripts/Runtime/Extensions/ObjectExtensions.cs:15)
BoundfoxStudios.FairyTaleDefender.Infrastructure.RuntimeAnchors.ScriptableObjects.RuntimeAnchorBaseSO`1[T].get_ItemSafe () (at Assets/_Game/Scripts/Runtime/Infrastructure/RuntimeAnchors/ScriptableObjects/RuntimeAnchorBaseSO.cs:36)
BoundfoxStudios.FairyTaleDefender.Systems.InputSystem.SelectionController.GameplayActionsOnClick (UnityEngine.Vector2 position) (at Assets/_Game/Scripts/Runtime/Systems/InputSystem/SelectionController.cs:70)
BoundfoxStudios.FairyTaleDefender.Systems.InputSystem.ScriptableObjects.CallbackProcessors.GameplayActionsSO.OnClick (UnityEngine.InputSystem.InputAction+CallbackContext context) (at Assets/_Game/Scripts/Runtime/Systems/InputSystem/ScriptableObjects/CallbackProcessors/GameplayActionsSO.cs:19)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray`1[System.Action`1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at ./Library/PackageCache/com.unity.inputsystem@1.5.1/InputSystem/Utilities/DelegateHelpers.cs:46)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

NullReferenceException while executing 'performed' callbacks of 'Gameplay/Click[/Mouse/leftButton,/Mouse/position]'
UnityEngine.InputSystem.LowLevel.NativeInputRuntime/<>c__DisplayClass7_0:<set_onUpdate>b__0 (UnityEngineInternal.Input.NativeInputUpdateType,UnityEngineInternal.Input.NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate (UnityEngineInternal.Input.NativeInputUpdateType,intptr)

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Witzigerweise bekomme ich den auf dem TouchPad nicht nachvollzogen, aber ich mach einen NullCheck in die Methode. :)
