### ISSUE TITLE
[Bug]: Tooltips bleiben bei Szenenwechsel bestehen, ändern sich danach auch nicht mehr

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#345]
### Fehlerbeschreibung

Fährt man vor Szenenwechsel mit der Maus über einen Tooltip, wird dieser danach ständig an der Maus angezeigt und aktualisiert sich auch nicht mehr sobald über andere Elemente gefahren wird. 

### Wie kann man den Fehler reproduzieren?

Gameplay starten -> Mauszeiger über Katapultturm -> Warten bis Gegner Leben auf 0 reduziert haben -> Wechsel zu anderen Szenen

### Erwartetes Verhalten

- Tooltip verschwindet bei Szenenwechsel.
- Tooltip aktualisiert Inhalt bei erneutem Hovern über Elemente.

### Betriebssystem

Windows 10

### Sonstiges

![grafik](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/18291863/17ba54e3-5e2c-401e-bf26-96a1c3634cb9)

**Comment by ManuelRauber** [comment]
.meine-aufgabe
