### ISSUE TITLE
Gameplay: Türme platzieren während ein anderer Turm ausgewählt ist

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#348]
### Beschreibung

Sollten Türme "ausgewählt" bleiben, also sollte ihre Reichweite zum Beispiel weiterhin eingeblendet werden, während ein anderer Turm platziert wird?
Ist aktuell die einzige Möglichkeit mehrere Reichweiten gleichzeitig anzuzeigen.
Würde vermutlich auch zu Konflikten führen wenn wir mehr im UI zum Tower haben, oder?

Was würdet ihr Gameplay mäßig da erwarten, oder hättet ihr gerne?
https://github.com/BoundfoxStudios/fairy-tale-defender/assets/18291863/bf0c75cd-7edb-438d-9450-f250a0d03e72

**Comment by ManuelRauber** [comment]
Tendenziell würd ich sagen:

## Möglichkeit 1: Kein Tower wird angezeigt
Selektierter Tower wird deselektiert und man sieht nur die Range vom eigenen Tower.

## Möglichkeit 2: Alle Tower zeigen ihre Range an
Beim Bauen zeigen alle anderen Tower ihre Range an, vielleicht etwas transparenter, sodass man seinen eigenen besser sehen kann.

Würde für den MVP sagen: Wir gehen mit Möglichkeit 1.

**Comment by ghost** [comment]
Ich finde die Anzeige der Reichweite, von den anderen Türmen, sehr nützlich! Aber Manu hat recht, für MVP ist Möglichkeit 1 ausreichend.

Möglichkeit 2 --> Feature!
