### ISSUE TITLE
Projektile sollten Flächenschaden verursachen können

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#351]
### Idee/Feature-Beschreibung

Aktuell verursachen Projektile nur auf einem Punkt Flächenschaden.
Wünschenswert wäre es, wenn größere Projektile wie die des Katapult, in der Lage wären auf einer größeren Fläche, bzw innerhalb eines größeren Radius Schaden zu verursachen.

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Hat @M4lph implementiert. :)
