### ISSUE TITLE
Spieler sollte einen Level gewinnen können

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#353]
### Idee/Feature-Beschreibung

Nachdem ein Level gestartet wurde, sollte das Spiel erkennen können, dass alle Gegner(wellen) gespawnt wurden und diese vom Spieler besiegt wurden oder es nicht geschafft haben das verbleibende Leben auf 0 zu reduzieren.

In dem Fall könnten Systeme wie das UI reagieren und eventuell verschiedene Statistiken auflisten, ein spezieller Audio Effekt könnte abgespielt werden etc.

Anschließend sollte man entweder zurück ins Menü navigieren können, oder eventuell auch den nächsten Level direkt starten.

- [x] #411 (Technische Implementierung)
- [x] #414 (Visuelles Feedback)

**Comment by M4lph** [comment]
So nach 4Monaten würde ich mich dann evtl mal an den Issue ranmachen :)
Hätte aber ein paar Fragen noch vorab. Geplant war ja z.B. bei Welle 20 nächstes Lvl freischalten, bei 30, 40 usw dann Achievment Sterne oder Ähnliches. Aktuell spawnen die Wellen aber direkt aneinander gereiht. D.h. ohne dass man eine Welle besiegt haben muss, kann also schon die nächste theoretisch spawnen. Soll das so bleiben, oder war das nur "zum Testen"? Wann sollte man genau diese Sachen freischalten? Beim Spawnen/ Erreichen von Welle X, oder zu dem Zeitpunkt an dem alle Monster dieser Welle besiegt wurden? Oder andere Ideen? :)

**Comment by ManuelRauber** [comment]
>  Soll das so bleiben, oder war das nur "zum Testen"? Wann sollte man genau diese Sachen freischalten?

Das war nur zum Testen, eigentlic hwar der Plan, dass die Wellen pausieren und man dann selbst weiter klicken muss. Muss aber gestehen, dass ich gerade selbst nicht weiß, ob das noch so viel Sinn macht. 

Hab in letzter Zeit einige TD gespielt und bei keinem war es quasi so. Sondern immer, dass es automatisch weiter geht und man ggf. aber schneller eine Welle rufen kann. Das könnte ihc mir auch ganz gut vorstellen.

Zum Gewinnen muss der Spieler ja quasi eh alle Wellen besiegen/erreichen. 
Im Moment wuerde ich eher sagen einfach alle besiegen und alles weitere schauen wir dann. :)

**Comment by M4lph** [comment]
Erledigt mit #463
