### ISSUE TITLE
[Idee/Vorschlag]: Alternative zu Coins?!

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#368]
### Idee/Feature-Beschreibung

kurz auf Discord angesprochen schreibe ich es hier nieder, zur späteren Erinnerung & Besprechung:

Aktuell ist es ja so, dass man Coins erhält wenn ein Gegner eliminiert wird. Das finde ich so mal nicht passend zum Spielstyle 😄 , aber versteh' das es nur eine aktuelle Zwischenlösung darstellt.
Wie wäre es wenn irgendein Gimmick am Boden liegen bleibt das man mit dem Mauszeiger, welcher ja die Fee ist, aufheben muss (also mit der Maus drüber fährt, KEIN Mausklick) ? .... könnte etwas schwung in den Spiellauf bringen.

Vielleicht später auch zum Thema Schwierigkeitsgrad/-stufe interessant oder so.

Punkte zu besprechen:

- könnte es nervig sein? 
- verschwindet das Gimmick es nach einer gewissen Zeit? (wenn man nicht mit dem Mauszeiger/Glücksfee drüber fährt)
- wie sieht das Gimmick aus? (verschiedene Farben bei verschiedenen Gegner = mehr Punkte?)

**Comment by ManuelRauber** [comment]
@DIY-Blub Könntest Du eventuell ein Coin blendern? :)

**Comment by ghost** [comment]
Coins werden durch Gems ersetzt, ein entsprechendes Modell gibt es bereits und wird aktuell durch die Entwicklung umgesetzt.
![grafik](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/60984430/9c508d57-12cf-449a-9296-236fb883e517)
