### ISSUE TITLE
Mesh Import Warnungen

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#377]
### Beschreibung

![image](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/740791/7b1f2598-71cb-4690-ada6-1a1475b2a623)

**Comment by ghost** [comment]
Woher stammt die TreasureChest.fbx ... direkt aus der Campfire (Banditenlager/Lagerfeuer) Datei von twetaew4t ?
Die Schatztruhe und das Lagerfeuer muss ich noch optimieren, danach kommen die Objekte in eine Blendfile und dann sollte auch kein Fehler mehr kommen. :)

**Comment by ManuelRauber** [comment]
> Woher stammt die TreasureChest.fbx ... direkt aus der Campfire (Banditenlager/Lagerfeuer) Datei von twetaew4t ? Die Schatztruhe und das Lagerfeuer muss ich noch optimieren, danach kommen die Objekte in eine Blendfile und dann sollte auch kein Fehler mehr kommen. :)

Uhm, das muss ich vorher noch prüfen :))

**Comment by ghost** [comment]
sollte/könnte sich mit PR #380 erledigen. :-)
