### ISSUE TITLE
docs-Webseite, YouTube-Playlist wird nicht angezeigt

### ISSUE THREAD

**Issue by ghost** [BoundfoxStudios/community-project#378]
### Beschreibung

Auf der [Webseite](https://docs.fairytaledefender.de/) ganz unten steht:
> Hier würde eine YouTube-Playlist gerendert werden. Allerdings hast Du keinen API-Key angeben.

**Comment by ManuelRauber** [comment]
Ich glaub das passiert zufällig, der API Key ist da und nach einem erneuten Build ging's auch wieder.
