### ISSUE TITLE
[Idee/Vorschlag]: Anzeige der Build-Version im MainMenu

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#40]
### Idee/Feature-Beschreibung

Im MainMenu soll eine Text-Anzeige sein, die die aktuelle Build-Version anzeigt.

Die Anzeige soll unten rechts platziert sein mit 25 px Abstand zum Rand.

Die Build-Nummer ist in der Datei `_Game/Build/manifest.json` gespeichert.
Es existiert bereits eine Klasse [BuildManifestReader](https://github.com/BoundfoxStudios/community-project/blob/develop/CommunityProject/Assets/_Game/Scripts/Runtime/Build/BuildManifest/BuildManifestReader.cs) zum Auslesen der JSON-Datei, die genutzt werden kann.

Zusätzlich soll es möglich sein auf diesen Text zu klicken um ihn in die Zwischenablage zu kopieren.

**Comment by ThKattanek** [comment]
Welches ist die Build-Nummer? 
  "runId": 13371337,
  "runNumber": 815
Oder fehlt diese noch?

**Comment by ThKattanek** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Ups, das kommt davon, wenn man den halben Tag über den Build guckt und dann ein Issue schreibt 😅

Am besten nutzen wir Application.Version + die ShortSha, so in Richtung "Build: 1.2.3 (shortsha)".
