### ISSUE TITLE
Kontrollieren ob im Build die Position der Animation des Cursors stimmt.

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#407]
### Idee/Feature-Beschreibung

Im Editor ist unter gewissen Umständen die Animation des Cursors verschoben, wenn zB. die Auflösung auf Free Aspect gestellt ist.

Müsste im Build kontrolliert werden, ob die Position bei verschiedenen Auflösungen korrekt am Cursor ist.

**Comment by ManuelRauber** [comment]
![image](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/740791/df66c0fd-1b81-4fbd-8efd-acc67c06dd4b)

Auf dem Mac-Build ist's auch verschoben.

**Comment by ManuelRauber** [comment]
Ich schnapp mir den Mal, hab's ja quasi auch verbockt. :)
