### ISSUE TITLE
Ballista Turm Änderungen

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#409]
### Idee/Feature-Beschreibung

Der Ballista-Turm benötigt einige visuelle Änderungen.

Die Idee ist, dass dieser Turm der erste Turm ist, der sich 360 ° rotieren kann, um in alle Richtungen zu schießen. Gleichzeitig soll die Waffe nicht ballistisch ("im Bogen") abgeschossen werden, sondern direkt auf das Ziel feuern.

Das ist der aktuelle Turm:

![image](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/740791/7d15ff44-7cd8-433d-998f-5b1d8ff1da2c)

Durch das direkte Feuern der Ballista sähe es komisch aus, wenn deren Pfeil erst den Schlitten der Ballista aufwärts folgt, um dann direkt nach unten gefeuert zu werden. 

Hier sehe ich zwei Möglichkeiten, wie wir das verbessern könnten:

1. Der Schlitten der Ballista steht gerade
![image](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/740791/a7235248-6ef2-4f05-bd26-74ab6572a4a1)
2. Der Schlitten der Ballista ist beweglich. Ähnlich wie das Katapult kann die Ballista den Schlitten bewegen und so exakt auf das Ziel ausgerichtet werden. Dadurch erhalten wir natürlich eine eventuell etwas komische Darstellung der Ballista. 
![image](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/740791/db6d3ba3-eada-4eff-a62f-746f3b74e87a)

In beiden Fällen müsste die Ballista im Idealfall über den Turm hinausragen (oder wir brauchen einen anderen Turm, der die Ballista trägt), sodass es visuell nicht aussieht, als schießt der Turm gegen die eigene Mauer.

Streng genommen ist der Ballista-Turm der falsche Turm für einen direkten Beschuss. Vielleicht sollten wir stattdessen generell einen anderen Turm hernehmen, bspw. einen Kanonenturm? Bin aber auch fein damit, wenn wir etwas "von der Realität" abwandern. :-)

**Comment by ghost** [comment]
.meine-aufgabe

**Comment by ghost** [comment]
Entwurf und FBX Dateien wurden auf Discord hochgeladen.

**Comment by ManuelRauber** [comment]
> Entwurf und FBX Dateien wurden auf Discord hochgeladen.

Kümmere mich auch bald drum :-))

**Comment by ManuelRauber** [comment]
Ich nehm das Issue mal, damit der Bot nicht nervt. 😅
