### ISSUE TITLE
Ballista: Self-intersecting polygon

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#410]
### Beschreibung

Muss in Blender korrigiert werden:

![image](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/740791/99cd4089-a91c-440a-8ac8-d29bc67e0017)

**Comment by ghost** [comment]
.meine-aufgabe

**Comment by ghost** [comment]
Problem sollte behoben sein, die Datei liegt aktuell nur auf meinen PC. Wird mit #409 dann gelöst.
