### ISSUE TITLE
UI anzeigen bei Ende eines Levels.

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#414]
> wäre ein Anzeige mit was ähnlichem wie
> 
> "Danke fürs Spielen! ...Fehler & Verbesserungsvorschläge kannst du gerne auf Github oder auf Discord bekannt geben" ... LINK Github / LINK Discord Channel / LINK zurück zum Menü
> 
> nicht für den Anfang besser? :)

_Originally posted by @DIY-Blub in https://github.com/BoundfoxStudios/fairy-tale-defender/issues/411#issuecomment-1868061690_

Was würdet ihr sonst noch gerne sehen, sobald ein Level abgeschlossen wurde?
Statistiken, wie die Spielzeit, Anzahl an gebauten Türmen, besiegten Gegnern?

Link zum nächsten Level, und/oder selbes nochmal spielen?

            
Benötigt #411

**Comment by ghost** [comment]
Also ich finde Statistiken, wie "optimiert" man gespielt hat, extrem lästig. Ich versteh jedoch bei den Spieleherstellern, das man damit eine Herausforderung in die Köpfe erschafft (Ehrgeiz, Konkurrenzdenken). ... Stichwort: Punktesystem

Ein Punktesystem und ähnliches brauchen wir m.M.n. nicht. 

Die Gegenfrage wäre ob es eine Anzeige geben wird, unter dem Spiel oder vor dem Level, wieviele Wellen noch kommen. Oder eben nach dem Level, wieviele Wellen man besiegt hat. Was wäre hier euch lieber?

**Nachtrag:**
Wir wollten zwischen den Leveln "die Geschichte" weiter erzählen, somit brauchen wir schon einen Übergang oder auch nur eine Abblende zur Story.

**Comment by M4lph** [comment]
>Also ich finde Statistiken, wie "optimiert" man gespielt hat, extrem lästig. Ich versteh jedoch bei den Spieleherstellern, das man damit eine Herausforderung in die Köpfe erschafft (Ehrgeiz, Konkurrenzdenken). ... Stichwort: Punktesystem

Ich weiß was du meinst, in den meisten Spielen mit Statistiken kümmere ich mich auch nicht darum, aber in manchen reizt es dann doch.. Irgendwann kommt dann der Punkt an dem man nicht mehr so entspannt spielt, obwohl entspannen/ abschalten eigtl der Anlass zum Zocken war. Ist wohl aber auch eher bei Online Leaderboards so, wie bei einfachen persönlichen Statistiken.

>Die Gegenfrage wäre ob es eine Anzeige geben wird, unter dem Spiel oder vor dem Level, wieviele Wellen noch kommen. Oder eben nach dem Level, wieviele Wellen man besiegt hat. Was wäre hier euch lieber?

Meinetwegen gerne an allen 3 Stellen. Hier könnte man dann dem Spieler ja auch ggf. die Möglichkeit geben während des Lvl besiegte/verbleibende Wellen ein-/auszublenden.

>Wir wollten zwischen den Leveln "die Geschichte" weiter erzählen, somit brauchen wir schon einen Übergang oder auch nur eine Abblende zur Story.

Die Möglickeit das vor/nach dem einblenden anderer Spielelemente zu implementieren sollten wir weiterhin haben, dürfte von keiner der bisherigen anderen Ideen ausgeschlossen werden.

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by M4lph** [comment]
Ist noch in Arbeit :)
