### ISSUE TITLE
[Idee/Vorschlag]: Hotkeys zum bauen von Türmen während des Spielens.

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#421]
### Idee/Feature-Beschreibung

Aktuell muss man zum Bauen eines Turmes dessen Button im UI anklicken, sodass man ihn platzieren kann.
Schön wäre es wenn man als Spieler z.B. Taste 1 drücken kann, womit der erste verfügbare Turm ausgewählt wird, bereit zum platzieren.

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by M4lph** [comment]
Wurde mit #436 erledigt, habe ich leider vergessen zu verknüpfen.

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Hallo

**Comment by ManuelRauber** [comment]
test

**Comment by ManuelRauber** [comment]
test
