### ISSUE TITLE
[Idee/Vorschlag]: Weitere Möglichkeiten für eine Waffe ihr Ziel auszuwählen.

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#422]
### Idee/Feature-Beschreibung

Aktuell kann eine Waffe ihr Ziel zufällig auswählen, anhand der verbleibenden Lebenspunkte (höchste/ niedrigste), und den Gegner der am nähesten zur Waffe ist.
Vorstellbar wären z.B. auch noch der Gegner der am weitesten zum Ziel fortgeschritten ist, oder das Gegenteil - der Gegner der es noch am weitesten hat bis zum Ziel.

**Comment by ManuelRauber** [comment]
Yes :)

**Comment by M4lph** [comment]
.meine-aufgabe
