### ISSUE TITLE
Namen von Tests anpassen.

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#428]
> Sowas wie Methode_ErwartetesVerhalten_Bedingung finde ich persönlich ansprechender, in der Weise sind auch die meisten bisher benannt. Aber du hast die meisten Tests geschrieben, wirst wohl auch noch die meisten schreiben, und bist Project Owner :) Also ich passe mich da einfach an dann 👍

Passt für mich aber auch, wenn wir die Underscore-Variant wählen, das dürfte besser lesbar sein. 
Ich mach ein Ticket, um die Name anzupassen. :)

_Originally posted by @ManuelRauber in https://github.com/BoundfoxStudios/fairy-tale-defender/issues/427#issuecomment-1886726602_

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by M4lph** [comment]
In der asmdef ist als Rootnamespace nicht der vollständige Pfad angegeben, bei allen anderen glaube ich schon.
![grafik](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/18291863/f018fcd9-4f43-4e3b-84e4-0c3cd076c9d5)

Soll ich den auch gerade noch mit anpassen?
BoundfoxStudios.FairyTaleDefender.Tests.Runtime?

**Comment by ManuelRauber** [comment]
> In der asmdef ist als Rootnamespace nicht der vollständige Pfad angegeben, bei allen anderen glaube ich schon. ![grafik](https://private-user-images.githubusercontent.com/18291863/295868806-f018fcd9-4f43-4e3b-84e4-0c3cd076c9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Njc0MjgsIm5iZiI6MTcwNDk2NzEyOCwicGF0aCI6Ii8xODI5MTg2My8yOTU4Njg4MDYtZjAxOGZjZDktNGY0My00ZTNiLTg0ZTQtMGMzY2QwNzZjOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA5NTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YTNkY2Y3M2Y2NjU2YjZiNTllMTQ5OWUxZGFkNzAyMmU0N2IzNTM1YjFhN2IwNzZmOWMyYmQwZDI2MGZiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RvqA1jNLZoD_aNdl_Qn2znvlV80U5Kmcn8NmBnFt1Gw)
> 
> Soll ich den auch gerade noch mit anpassen? BoundfoxStudios.FairyTaleDefender.Tests.Runtime?

Ich würde fast behaupten, dass das bei der asmdef für die normale Runtime (also nicht tests) genau so ist. :)

Ist gewollt so, weil ich kein "Runtime" im Namespace haben will für das "normale". 
Nur bei Editor steht's mit drin, damit's eben im Editor-Namespace ist.

**Comment by M4lph** [comment]
> Ich würde fast behaupten, dass das bei der asmdef für die normale Runtime (also nicht tests) genau so ist. :)

Jepp, hab ich wohl übersehen.

> Ist gewollt so, weil ich kein "Runtime" im Namespace haben will für das "normale".

Okidoki 👍
