### ISSUE TITLE
Prüfen, warum der Linux-Build fehlschlägt.

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#429]
### Beschreibung

Prüfen, warum der Linux-Build fehlschlägt.

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Aktueller Stand: Scheint ein Problem mit Mono zu sein, warum auch immer.
Wir probieren jetzt, GameCI zu nutzen via Docker auf TeamCity.

**Comment by ManuelRauber** [comment]
Linux-Variante via Docker scheint erstmal zu Bauen.
Warten wie auf das Steam-Deployment und dann kann @DIY-Blub es mal ausprobieren :)

**Comment by ghost** [comment]
@ManuelRauber hab gerade das Update durchgeführt..... naja, das Spiel belegt nun auf meiner Festplatte 0 Byte. Da ist wohl etwas schief gegangen :)
Auch nach einem Neustart von Steam kommt nicht mehr als ein "Fehler beim Ausführen" vom Game.

**Comment by ManuelRauber** [comment]
> @ManuelRauber hab gerade das Update durchgeführt..... naja, das Spiel belegt nun auf meiner Festplatte 0 Byte. Da ist wohl etwas schief gegangen :) Auch nach einem Neustart von Steam kommt nicht mehr als ein "Fehler beim Ausführen" vom Game.

@DIY-Blub Es ist auch noch nicht aktualisiert 🙈 
Ich sag Dir Bescheid, wenn's soweit ist :)

**Comment by ManuelRauber** [comment]
Das Bauen des Builds funktioniert wieder, aber der Build selbst noch nicht. 

Info von @DIY-Blub:

> KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum
OPENGL LOG: Creating OpenGL 4.5 graphics device ; Context level  <OpenGL 4.5> ; Context handle 21765784
**ERROR: Shader Hidden/Universal Render Pipeline/DBufferClear shader is not supported on this GPU (none of subshaders/fallbacks are suitable)**

**Comment by ManuelRauber** [comment]
Blockiert: Manu wartet auf Lieferung vom Steam Deck

**Comment by ManuelRauber** [comment]
Aktueller Stand: 

- Spiel läuft auf Steam Deck, allerdings ohne Shader für das Reichweitendecal. -> Ich hab hierfür mal ein Issue angelegt: #460 
- Spiel baut auch wieder TeamCity, setzen von `-buildTarget Linux64` wurde benötigt beim Build.
