### ISSUE TITLE
Hotkey Rebinding

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#438]
### Idee/Feature-Beschreibung

Wir haben im Spiel einige Tasten, die man eventuell neu binden können sollte.

- WSAD -> Kamera
- 0-9 -> Tower 1..10 bauen (wir haben aktuell nur 2).

Dafür bräuchte es:

- [ ] In den Optionen mindestens mal eine Anzeige aktueller Hotkeys
- [ ] Die Möglichkeit, die Hotkeys neu zu binden. Hier muss man schauen, welche Möglichkeiten das neue Unity-Input-System bietet, die bringen da schon irgendwas mit.

**Comment by M4lph** [comment]
Wie soll hier mit alternativen Keybinds umgegangen werden?
Camera Movement hat derzeit sowohl WSAD als auch die Arrow Keys als Bindings.
Soll man Spielern hier die Möglichkeit geben für jede Action zweite Belegung zu wählen? Würde wohl auch Refactoring der Keybinds für TowerBuilding erforden, da diese mit dem Index des jeweiligen Bindings arbeiten.

Wie soll mit Konflikten bei doppelter Belegung in verschiedenen Action Maps umgegangen werden? (Siehe PauseGame Problematik => Wenn Pause/Resume Game in verschiedenen Maps auf selben Key sind, wird State durchgereicht.)

**Comment by ManuelRauber** [comment]
> Wie soll hier mit alternativen Keybinds umgegangen werden?

Ich würde sagen, wir entfernen die alternativen Keybinds auf den Arrow Keys. Wenn das jemand so wollen würde, könnte man es in den Optionen einstellen.

> Soll man Spielern hier die Möglichkeit geben für jede Action zweite Belegung zu wählen?

Nein.

> Wie soll mit Konflikten bei doppelter Belegung in verschiedenen Action Maps umgegangen werden?

Der einfachste Weg (hoffentlich) sollte sein, dass wir generell kein doppeltes Belegen von Keybinds erlauben. Egal, in welcher Action Map er drin ist.

**Comment by M4lph** [comment]
.meine-aufgabe
