### ISSUE TITLE
Dynamischer UI-Aufbau der baubaren Türme

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#439]
### Idee/Feature-Beschreibung

Aktuell ist das UI für die baubaren Türme hart implementiert.

Wir haben mit #436 im LevelSO eine Möglichkeit geschaffen, dass über das SO bestimmt wird, welche Türme im Spiel baubar sind.
Daher sollte mit diesem Issue eine Änderung implementiert werden: Das UI sollte sich automatisch erstellen mit den Angaben der Türme im LevelSO.

**Comment by M4lph** [comment]
.meine-aufgabe
