### ISSUE TITLE
Entscheidung über die Art von Save Games

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#442]
Es gibt zwei Arten von Save Games, die wir Implementieren können:

## Implizit

Kennt man oft von Mobile Games, das Spiel wird implizit einfach gespeichert und man hat keine Möglichkeit, verschiedene Spielstände anzulegen.
Möchte man neu Beginnen, kann in den Optionen das gesamte Spiel zurückgesetzt werden.

## Slot-basiert

Klassisch, wie man es von anderen Spielen kennt, kann der Benutzer, wenn er ein neues Spiel erstellt, einen von 3? Slots auswählen, in dem sein Spiel dann automatisch gespeichert wird. 
Das ist oft dann praktisch, wenn man zu Beginn des Spiels verschiedene Parameter setzen kann, wie z.B. den Schwierigkeitsgrad. 

Hat man alle drei Slots belegt, oder möchte einen zurücksetzen, so kann man im Menü einen Slot löschen.

---

## Beliebig viele Save Games

Der Vollständigkeit halber könnte man natürlich auch dem Benutzer erlauben beliebig viele eigene Spielstände anzulegen. Das wäre jedoch für unsere Art von Spiel recht unüblich.

**Comment by ManuelRauber** [comment]
Alternativ könnte man auch eine Kombination machen: 

Wir implementieren es so, als wären es slots, aber benutzen automatisch immer nur den ersten, solange wir keine unterschiedlichen Parameter haben. Das macht es einfach das ganze zu erweitern, falls wir später doch mal verschiedene Startparameter haben.

**Comment by ManuelRauber** [comment]
test

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
noch ein test

**Comment by ManuelRauber** [comment]
@M4lph was denkst du?

**Comment by M4lph** [comment]
Ich bin am schwanken zwischen einem einzigen impliziten Spielstand und der Kombination mit den Slots, die du noch vorgeschlagen hast. 
Von der Vorstellung her, die ich bisher so von den Ideen auf dem Miro Board usw habe, wie der Spielablauf etc aussehen soll, sehe ich es fast eher bei nur einem Spielstand. 
Was wären denn deine Gedanken hierzu, bzw was würdest du bevorzugen?

**Comment by ManuelRauber** [comment]
> Ich bin am schwanken zwischen einem einzigen impliziten Spielstand und der Kombination mit den Slots, die du noch vorgeschlagen hast. Von der Vorstellung her, die ich bisher so von den Ideen auf dem Miro Board usw habe, wie der Spielablauf etc aussehen soll, sehe ich es fast eher bei nur einem Spielstand. Was wären denn deine Gedanken hierzu, bzw was würdest du bevorzugen?

Ja, das würde für mich auch passen. 

Das wäre ja denn die Kombination aus den ersten beiden Dingen 👍

**Comment by ManuelRauber** [comment]
Siehe #457
