### ISSUE TITLE
RuntimeSets müssen geleert werden

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#485]
### Beschreibung

Aktuell haben wir folgendes Problem:

1. Level starten.
2. Warten bis einige Gegner gespawnt wurden.
3. Level über Pause-Button verlassen.
4. Level erneut starten.

Level kann nicht mehr gewonnen werden, da die RuntimeSets noch mit Gegnern aus der Runde zuvor beladen sind.

Wir müssen am Ende eines Levels/Verlassen des Levels alle RuntimeSets wieder leeren.

**Comment by M4lph** [comment]
.meine-aufgabe
