### ISSUE TITLE
Erstellung einer Scene für Credits

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#50]
### Beschreibung

Erstellung einer klassischen Credits-Scene:

- [ ] Scrollender Text, genauer Text siehe unten
- [ ] Button, um zum Menü zurück zu kehren
- [ ] Auflistung aller Contributors (siehe Klasse `ContributorsReader` um diese zu laden)
- [ ] Links sollen klickbar sein

Die Credits werden _nicht_ übersetzt.

## Text/Reihenfolge

1. Boundfox Studios
2. Community-Projekt
3. Link zum YouTube-Kanal: https://youtube.com/c/boundfox
4. Link zu GitHub: https://github.com/boundfoxstudios/community-project
5. Auflistung der Contributors: Name des Contributors ist klickbar mit einem Link zu seinem Profil

**Comment by ThKattanek** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
> .meine-aufgabe

Das geht nur bei Issues, die nicht "Triage" als Label haben :)

**Comment by ThKattanek** [comment]
Hatte ich dann mitbekommen :)

**Comment by ManuelRauber** [comment]
> Hatte ich dann mitbekommen :)

Nun kannst :)

**Comment by ThKattanek** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Obige Nachricht war nur ein Test, um zu schauen, ob es geht. :)
PR wurde durch @ThKattanek bereits gestellt :)

**Comment by ThKattanek** [comment]
Habe gerade keine Zeit, werde das aber noch umsetzen.

**Comment by ThKattanek** [comment]
Bei mir ist privat etwas dazwischen gekommen, ich komme die nächste Zeit nicht dazu hier weiter zu machen. Es kann ruhig ein anderer dieses issue übernehmen.

**Comment by fastFox2** [comment]
.meine-aufgabe

**Comment by fastFox2** [comment]
Ich implementiere erst mal mit einer vorläufigen UI, das Design ja noch fehlt? Siehe https://github.com/BoundfoxStudios/community-project/issues/64

**Comment by ManuelRauber** [comment]
> Ich implementiere erst mal mit einer vorläufigen UI, das Design ja noch fehlt? Siehe #64

Japp, das würde erstmal reichen. 
Schau auch gerne hier in die Kommentare: https://github.com/BoundfoxStudios/community-project/pull/90 Hab das eine oder andere schon geschrieben, wie eine Umsetzung ausschauen könnte.
