### ISSUE TITLE
Erstellung des MainAudioMixers

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#60]
### Idee/Feature-Beschreibung

Für die Soundausgabe benötigt das Projekt einen [AudioMixer](https://docs.unity3d.com/Manual/AudioMixer.html).

Dieser soll folgende Kanäle beinhalten:

- [ ] Music
- [ ] UI
- [ ] Effects

Alle drei sollen ihr Volume als Parameter freigeben:

- [ ] MusicVolume
- [ ] UIVolume
- [ ] EffectsVolume

Name des Mixers:

- [ ] MainAudioMixer

**Comment by BlackJack237** [comment]
.meine-aufgabe
