### ISSUE TITLE
Implementierung BackgroundMusicPlayer

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#61]
### Idee/Feature-Beschreibung

Implementierung eines BackgroundMusicPlayer (BMP).

## Playlist

* ScriptableObject zur Verwaltung von mehreren PlaylistItems
* Anfänglich werden wir sicher nur eine Playlist haben, aber vielleicht später mal mehr, thematische, etc. 

## PlaylistItem

* ScriptalbleObject mit folgenden Infos:
  * AudioClip
  * Interpret
  * Songname
  * Optional: URL zum Interpret

Die Infos aus dem PlaylistItem könnte man später für die Generierung der Credits in der Credits-Szene (#50) benutzen.

## BMP

* MonoBehaviour, lebt in der PersistentScene
* Soll direkt im Awake anfangen, Musik aus einer Playlist abzuspielen
* Spielt zufällig einen Song aus der Playlist, aber niemals 2x das gleiche nacheinander
* Gibt Audio über den MainAudioMixer auf dem Kanal "Music" aus (#60)

**Comment by M4lph** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Hey @M4lph 

Ich hab eben die #60 gemerged mit dem MainAudioMixer, den wirst Du ja brauchen für die Implementierung vom BMP. :)

Zu finden dann unter Settings/Audio/MainAudioMixer

**Comment by M4lph** [comment]
Hey.
Hatte ich auch im Auge, aber Danke für's Bescheid geben.

Ein paar Fragen hätte ich schonmal bevor ich mich an die Implementierung mach und mir sicher noch mehr einfallen :)

-`Anfänglich werden wir sicher nur eine Playlist haben, aber vielleicht später mal mehr, thematische, etc.` 
Erstmal nach YAGNI vorgehen? Playlist also nur über Inspektor zuweisbar, oder schon Grundstein legen um auch zur Runtime switchen zu können etc? Beispiel: Level Wechsel o.Ä.
-Playmode auch erstmal YAGNI? Also nur Rnd ohne doppelte?

Zur Impementierung der PlayListItems noch ein paar Gedanken/Fragen:
-  Wie die Interpreten/deren Link(s?) machen? Bei dem Titel als einfachen String in jedem SO geh ich noch mit, Aber spätestens bei wiederholenden Interpreten/deren Links wird sehr fehleranfällig.
Naheliegend wäre ja die Contributor Klasse hier auch iwie zu nutzen. Aber wie diese dann "füllen"? Die Reader Klasse erweitern, wozu auch andere Datei wie die autogenerierte GitHub notwendig wäre oder anderen Helper erstellen? 
SO's auch hierzu wären sicher auch eine Alternative, dann haste halt wieder mehr im Editor zu tun, für pure "Sound Designer" evtl nicht so einfach zugänglich etc...

Hat da jmd schon einen guten Rat für mich? :)

**Comment by ManuelRauber** [comment]
@M4lph 

> Playlist also nur über Inspektor zuweisbar, oder schon Grundstein legen um auch zur Runtime switchen zu können etc? 

Bitte YAGNI :) Ich wollte mit der Aussage nur begründen, warum ich die Indirektion über eine separate Playlist haben möchte (auch wenn wir das eventuell nie brauchen, allerdings ist die Implementierung jetzt am Anfang einfacher, als eventuell später umbauen zu müssen) und nicht einfach eine Liste in einem Manager oder so. :)

> -Playmode auch erstmal YAGNI? Also nur Rnd ohne doppelte?

Yes, wie beschrieben, Random, ohne das zweimal nacheinander das gleiche kommen kann.

> Wie die Interpreten/deren Link(s?) machen? Bei dem Titel als einfachen String in jedem SO geh ich noch mit, Aber spätestens bei wiederholenden Interpreten/deren Links wird sehr fehleranfällig.

Prinzipiell stimme ich Dir hier zu, sehr guter Gedankengang! 

Ich denke jedoch, dass wir nachher nur eine Handvoll von Musik haben und eventuell gar nicht so oft sich wiederholende Interpreter. Insofern würde ich vorschlagen, dass wir hier den einfachsten Weg gehen und dies auch als Strings hinterlegen. 

Die Autogenerierung über GitHub/contributors.json wüsste ich ehrlich gesagt nicht, wie man dort sinnvoll rausfinden sollte, wer was contributed hat. Über bestimmte Labels in den Commit-Messages würde ich hier nur ungern gehen.

> [...] für pure "Sound Designer" evtl nicht so einfach zugänglich etc...

Das ist nicht tragisch. Generell, so hab ich's auch in der Doku hinterlegt, packen Artists ihre Assets in einen Ordner außerhalb vom Editor und ein Dev muss sie dann später in den Editor integrieren. Klar, wenn ein Artist sich mit Unity auskennt und sich das zutraut, es direkt zu integrieren, kein Problem. Ansonsten wird's immer ein Unity-Kundiger tun. :)
