### ISSUE TITLE
Implementierung JsonFileManager

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#67]
### Beschreibung

Im Laufe des Projekts werden wir Dateien auf die Festplatte schreiben und lesen müssen.
Dazu implementieren wir im ersten Schritt einen Json-basierten FileManager, sodass wir es leichter haben zu prüfen, was auf die Festplatte geschrieben wird. Später tauschen wir diesen eventuell gegen einen BinaryWriter aus, sodass die Daten auf der Festplatte nicht mehr so einfach zu ändern sind.

Daher soll der JsonFileManager folgendes Interface implementieren:

```cs
public interface IFileManager
{
  UniTask<bool> ExistsAsync(string key);
  UniTask WriteAsync(string key, object serializable);
  UniTask<T> ReadAsync<T>(string key);
}
```

Als Basispfad nutzen wir `Application.persistentDataPath`.

Weiter soll mit dieser Aufgabe auch ein neues Menü-Item angelegt werden, dass via `EditorUtility.RevealInFinder` den Pfad öffnet, sodass man schnell im Explorer/Finder sehen kann, ob und welche Dateien wir abspeichern.

**Comment by fastFox2** [comment]
.meine-aufgabe
