### ISSUE TITLE
Backend-Implementierung von generischen Spieloptionen

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#68]
### Idee/Feature-Beschreibung

Mit dieser Aufgabe sollen weitestgehend generische Spieloptionen implementiert werden, aktuell erstmal ohne UI, da das generelle UI-Design (siehe #64) noch fehlt. 

Benötigt zur Implementierung #67.

Dennoch können wir bereits im Hintergrund, aka Backend, einige typische Optionen implementieren:

* Auflösung
* Einstellung der Grafikqualität. Hier starten wir erstmal mit den drei Standard-Optionen von URP:
  * Performance
  * Balanced
  * High Fidelity
* Lautstärkeregelung (siehe #60):
  * Master 
  * Musik
  * Effekte
  * UI  

### ScriptableObject

Für die Optionen soll ein ScriptableObject angelegt werden, welches wir dann innerhalb vom Spiel nutzen. Wird das Spiel beendet, müssen die aktuellen Optionen, die im SO stecken, serialisiert und auf die Festplatte geschrieben werden. Wird das Spiel gestartet, müssen diese Daten wieder eingelesen und im SO abgelegt werden. Das Laden geschieht einmalig in der Initialization-Scene (und damit im `InitializationLoader`) und einmal im `EditorColdStartup`, in beiden Fällen so früh wie möglich, sodass nachfolgende Systeme bereits Zugriff auf die gespeicherten Daten haben.

Allerdings soll nicht das komplette SO serialisiert werden, sondern nur ein innenliegender Datencontainer:

```cs
public class BeispielSO : ScriptableObject
{
  private DataContainer _dataContainer;

  public AudioSettings Audio => _dataContainer.Audio;

  public async UniTask LoadAsync()
  {
    // Laden
  }

  public async UniTask SaveAsync()
  {
    // Speichern
  }

  [Serializable]
  public class AudioSettings
  {
    [Range(0, 1f)]
    public float MasterVolume = 1f;
  }

  [Serializable]
  private class DataContainer 
  {
    public AudioSettings Audio;
  }
}

// Zugriff dann später z.B. via:
public class Beispiel2: MonoBehaviour
{
  [SerializeField]
  private BeispielSO Beispiel;

  private void Awake()
  {
    MainAudio.SetParameter("MasterVolume", Beispiel.Audio.MasterVolume);
  }
}
```

### GameSettingsManager

In der PersistentManagers-Scene soll ein MonoBehaviour implementiert werden, dass die Einstellungen, die im SO getroffen wurden, auf das Spiel anwendet.

Als Information (wird erst mit dem UI relevant) soll dieser auf ein Event reagieren, wann immer sich die Spieleinstellungen geändert haben und diese entsprechend anwenden.

**Comment by M4lph** [comment]
.meine-aufgabe
