### ISSUE TITLE
Implementierung InputReaderSO

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#69]
### Beschreibung

Mit dieser Aufgabe soll ein InputReaderSO entwickelt werden, der bereits ein paar Steuerung versteht und diese als Event bereitstellt. Die Grundlage für den InputReaderSO bildet dieses [Tutorial](https://www.youtube.com/watch?v=hVti7KGHwWI).

Zum aktuellen Zeitpunkt können folgende Dinge bereits implementiert werden:

- [ ] Kamera-Bewegung mit WSAD
- [ ] Kamera-Bewegung mit Maus am Bildschirmrand

Diese Aktionen sollen in der ActionMap "Camera" abgelegt werden.
Beide Aktionen lösen ein Event `CameraMove<Vector2>` aus.

Den aus der Bewegung resultierenden Vector2, der an CameraMove übergeben wird, soll via [ClampMagnitude](https://docs.unity3d.com/ScriptReference/Vector2.ClampMagnitude.html) auf eine maximale Länge von 1 beschränkt werden, sodass die diagonale Bewegung nicht schneller ist, als eine nicht-diagonale Bewegung. 

Zusätzlich sollen zwei Methoden bereitstehen, um alle spielrelevanten ActionMaps zu (de)aktivieren.

Der InputReaderSO muss getestet werden, dazu bitte [hier](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.4/manual/Testing.html) lesen, wie es funktioniert.

```mermaid
flowchart LR
  WSAD -->|Invoke| CameraMove
  Maus[Maus am Bildschirmrand] -->|Invoke| CameraMove
  CameraMove <-->|Subscribe| CameraController
```

Die Implementierung vom CameraController erfolgt in einem eigenen Issue:

- [x] #190

**Comment by Salja** [comment]
.meine-aufgabe

**Comment by ManuelRauber** [comment]
Vorerst zurück nach Triage, bis wir wissen, was für eine Art von Kamera und Inputs wir benötigen.

**Comment by ManuelRauber** [comment]
.meine-aufgabe
