### ISSUE TITLE
Contributors sollten ihre Aufgabe wieder zurückgeben können

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#78]
### Beschreibung

Jeder Contributor sollte via `.aufgabe-zurückgeben` eine Aufgabe wieder zurückgeben können.

**Comment by ManuTutorial** [comment]
.meine-aufgabe

**Comment by ManuTutorial** [comment]
Muss nur dokumentiert werden, da man sich selbst wieder unassignen kann:

![image](https://user-images.githubusercontent.com/113589585/194323536-5807b921-6616-4f78-983d-1a26cddf1133.png)
