### ISSUE TITLE
[Idee/Vorschlag]: Coding Conventions erweitern

### ISSUE THREAD

**Issue by M4lph** [BoundfoxStudios/community-project#85]
### Idee/Feature-Beschreibung

Konstanten werden laut Unity UOP Coding conventions im ScreamCase genutzt, wir haben derzeit PascalCase.

Wir sind auch bei der Nutzung von privaten Feldern in Verbindung mit [SerializeField] Attribut inkonsistent. Vllt den Fall auch noch in den Coding Conventions aufführen.

**Comment by ManuelRauber** [comment]
> Konstanten werden laut Unity UOP Coding conventions im ScreamCase genutzt, wir haben derzeit PascalCase.

Japp, das hab ich rausgenommen, mag ich persönlich nicht. :)

> Wir sind auch bei der Nutzung von privaten Feldern in Verbindung mit [SerializeField] Attribut inkonsistent. Vllt den Fall auch noch in den Coding Conventions aufführen.

Das ist korrekt, das fehlt tatsächlich! :)
