### ISSUE TITLE
Implementierung AudioCue-System

### ISSUE THREAD

**Issue by ManuelRauber** [BoundfoxStudios/community-project#89]
### Beschreibung

Das AudioCue-System dient zum Abspielen von Sound-Effekten, bspw. wenn ein Gegner getroffen wird, stirbt oder ähnliches. 

Solche Effekte sollten über ein zentrales System abgespielt werden und nicht direkt beim betroffenen GameObjekt. Bleiben wir beim Beispiel des Tod's eines Gegners. Wenn ein Gegner stirbt, wird er in der Regel entweder via `Destroy` aus der Scene entfernt oder zumindest deaktiviert. D.h. auch jegliches Sound, der durch dieses GameObject abgespielt wird, wird deaktiviert. Dadurch wird der Sound unterbrochen. D.h. man müsste entweder warten mit der Deaktivierung des GameObjects oder eben den Sound über ein AudioCue-System abspielen.

# Implementierungsdetails

Dazu müssen folgende Dinge implementiert/angelegt werden:

- [ ] AudioCueSO
- [ ] SoundEmitterPrefab
- [ ] AudioCueEventChannelSO
- [ ] AudioCuePlayer

## AudioCueSO

- [ ] Ablegen unter `Scripts/Runtime/Audio/ScriptableObjects`
- [ ] Hat ein Feld für einen AudioClip

## SoundEmitterPrefab

- [ ] GameObject mit einer AudioSource
- [ ] AudioSource nutzt den MainAudioMixer und dort den Kanal "Effects"
- [ ] PlayOnAwake ausschalten
- [ ] Prefab ablegen unter `Prefabs/Audio`
- [ ] Benötigt eine öffentliche API zum Setzen des AudioClips der AudioSource
- [ ] Benötigt ein reines C#-Event, das ausgelöst wird, sobald der AudioClip abgespielt wurde

## AudioCueEventChannelSO

- [ ] Ablegen unter `Scripts/Runtime/Events/ScriptableObjects`
- [ ] Implementiert die Basis `EventChannelSO<T>`, wobei `T` ein `AudioCueSO` ist (siehe z.B. `BoolEventChannelSO`
- [ ] Eine Instanz des SO ablegen unter `ScriptableObjects/Events`

## AudioCuePlayer

- [ ] Script ablegen unter `Scripts/Runtime/Audio/AudioCuePlayer`
- [ ] GameObject in PersistentScene erzeugen und AudioCuePlayer anhängen
- [ ] GameObject als Static markieren
- [ ] Script benötigt
  - [ ] Ein Feld für `AudioCueEventChannelSO`
  - [ ] Ein Feld für `SoundEmitterPrefab`
  - [ ] Beim OnEnable an das Event anhängen (ein Beispiel findest Du im `SceneLoader`)
  - [ ] Beim OnDisable vom Event abhängen
  - [ ] Sobald das Event ausgelöst wird, muss:
    - [ ] Eine Instanz vom `SoundEmitterPrefab` erzeugt werden
    - [ ] Der AudioClip aus dem Event dem SoundEmitter übergeben werden
    - [ ] Den AudioClip abspielen
    - [ ] Sobald der AudioClip fertig ist, soll die Instanz des SoundEmitters wieder zerstört werden

# Wie kann ich das testen?

Da wir aktuell noch nichts haben, was einen Sound abspielen kann, kannst Du das ganze nur testen, wenn Du Dir ein weiteres Script machst, dir eine Instanz vom AudioCueSO anlegst und dann diese Instanz über das Event zum AudioCuePlayer schickst. Kostenfreie Soundeffekte zum Testen findest Du z.B. auf Zapsplat oder FreeSound. Bitte achte aber darauf, dass Du Deine Test-Skripte und Test-Assets nicht in den PR übernimmst.

**Comment by fastFox2** [comment]
.meine-aufgabe
